#.Travis.yml
language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_install:
  - chmod +x gradlew

before_deploy:
  - zip -r freebsr-springboot-webservice *
  - mkdir -p deploy
  - mv freebsr-springboot-webservice.zip deploy/freebsr-springboot-webservice.zip

deploy:
  - provider: s3
    access_key_id: AKIA57OHDUUD4USHNVMH
    secret_access_key: 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
    bucket: freebsr-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: AKIA57OHDUUD4USHNVMH
    secret_access_key: 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
    bucket: freebsr-springboot-build
    key: freebsr-springboot-webservice.zip
    bundle_type: zip
    application: freebsr-springboot-webservice
    deployment_group: freebsr-springboot-webservice-group
    region: ap-northeast-2
    wait-until-deployed: true
#CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - wjdals300@gmail.com